name: Java CI with Maven, SonarQube, and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build with Maven
        run: mvn -B package --file pom.xml
#
#      - name: Run SonarQube
#        run: mvn clean verify sonar:sonar -Dsonar.projectKey=${{secrets.SONAR_KEY}} -Dsonar.projectName=${{secrets.SONAR_HOST}} -Dsonar.host.url=${{secrets.SONAR_HOST}} -Dsonar.token=${{secrets.SONAR_TOKEN}}

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image with Docker compose
        run : sudo docker-compose build
        #run: sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-spring:latest .

      - name: Push Docker image to Docker Hub
        run: |
          sudo docker-compose push
        #run: sudo docker push ${{ secrets.DOCKER_USERNAME }}/hello-spring:latest

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "."
          target: "/home/ubuntu/test"

      - name: Stop existing containers on port 80 and 8080
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            ports_to_check=("80" "8080")
            for port in "${ports_to_check[@]}"; do
              existing_container=$(sudo lsof -i:$port -t)
              if [ ! -z "$existing_container" ]; then
                sudo docker stop $existing_container
                sudo docker rm $existing_container
              fi
            done

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/ubuntu/test
            docker-compose pull
            docker-compose down || true
            docker-compose up -d
#            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/hello-spring:latest
#            sudo docker stop hello-spring || true
#            sudo docker rm hello-spring || true
#            sudo docker run -d --name hello-spring -p 8080:8080 -p 6379:6379 -p 1433:1433 -p 80:80 ${{ secrets.DOCKER_USERNAME }}/hello-spring:latest